name: CI Pipeline   # Workflow name

on:
  push:
    branches: [ "feature/aws-s3-bucket-ecr" ]   # Trigger on push to this branch

jobs:
  build:
    runs-on: ubuntu-latest # GitHub runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Pull repo code

      - name: Set up JDK
        uses: actions/setup-java@v3 # Install Java
        with:
          java-version: '17'
          distribution: 'temurin'   # corrected distribution

      - name: Build with Maven
        run: mvn clean package -DskipTests # Build JAR

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: springboot-architecture-lab   # <-- replace with your ECR repo name
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG